-- Passenger table creation
CREATE TABLE PASSENGER (passenger_id NUMBER(10) PRIMARY KEY, 
full_name VARCHAR(200) NOT NULL, 
national_id VARCHAR(50) UNIQUE,
phone_number VARCHAR(20) NOT NULL);

-- bus table creation
CREATE TABLE bus (
    bus_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR2(20) NOT NULL UNIQUE,
    driver_name VARCHAR2(100),
    route VARCHAR2(100)
);

-- Emergency_contact table creation
CREATE TABLE EMERGENCY_CONTACT (
    contact_id NUMBER(10) PRIMARY KEY,
    passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
    contact_name VARCHAR2(200),
    relationship VARCHAR2(50),
    contact_phone VARCHAR2(20)
    );

-- Trip table creation
 CREATE TABLE TRIP (
    trip_id NUMBER(10) PRIMARY KEY,
    bus_id NUMBER(10) REFERENCES BUS(bus_id),
    departure_place VARCHAR2(200),
    destination_place VARCHAR2(200),
    trip_date DATE,
    departure_time VARCHAR2(10) 
    );

-- booking table creation
CREATE TABLE BOOKING (
   booking_id NUMBER(10) PRIMARY KEY,
   trip_id NUMBER(10) REFERENCES TRIP(trip_id),
   passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
   seat_number VARCHAR2(10),
   ticket_number VARCHAR2(50) UNIQUE
   );

-- Employees table creation
CREATE TABLE employees (
        employee_id NUMBER,
        username VARCHAR2(50) UNIQUE NOT NULL,
        position VARCHAR2(50),
        phone_number VARCHAR2(20),
        Email VARCHAR2(100),
        CONSTRAINT pk_employee PRIMARY KEY (employee_id)
    );

-- Holiday_calendar table creation
 CREATE TABLE holiday_calendar (
        holiday_id NUMBER,
        holiday_name VARCHAR2(100) NOT NULL,
        holiday_date DATE NOT NULL,
        holiday_type VARCHAR2(50),
        CONSTRAINT pk_holiday PRIMARY KEY (holiday_id)
    );

-- peims_Audit_log table creation
  CREATE TABLE PEIMS_AUDIT_LOG 
   (LOG_ID NUMBER PRIMARY KEY, 
	TABLE_NAME VARCHAR2(50), 
	OPERATION VARCHAR2(20), 
	USERNAME VARCHAR2(30), 
	ACTION_STATUS VARCHAR2(20), 
	ACTION_TIME DATE DEFAULT SYSDATE, 
	REASON VARCHAR2(200)
      );
	 -- Sequence for audit IDs
CREATE SEQUENCE audit_sequence START WITH 1 INCREMENT BY 1;
