-- Passenger table creation
CREATE TABLE PASSENGER (passenger_id NUMBER(10) PRIMARY KEY, 
full_name VARCHAR(200) NOT NULL, 
national_id VARCHAR(50) UNIQUE,
phone_number VARCHAR(20) NOT NULL);

-- bus table creation
CREATE TABLE bus (
    bus_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR2(20) NOT NULL UNIQUE,
    driver_name VARCHAR2(100),
    route VARCHAR2(100)
);

-- Emergency_contact table creation
CREATE TABLE EMERGENCY_CONTACT (
    contact_id NUMBER(10) PRIMARY KEY,
    passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
    contact_name VARCHAR2(200),
    relationship VARCHAR2(50),
    contact_phone VARCHAR2(20)
    );

-- Trip table creation
CREATE TABLE EMERGENCY_CONTACT (
   contact_id NUMBER(10) PRIMARY KEY,
   passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
   contact_name VARCHAR2(200),
   relationship VARCHAR2(50),
   contact_phone VARCHAR2(20)
   );

-- booking table creation
CREATE TABLE BOOKING (
   booking_id NUMBER(10) PRIMARY KEY,
   trip_id NUMBER(10) REFERENCES TRIP(trip_id),
   passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
   seat_number VARCHAR2(10),
   ticket_number VARCHAR2(50) UNIQUE
   );

-- Employees table creation
CREATE TABLE employees (
        employee_id NUMBER,
        username VARCHAR2(50) UNIQUE NOT NULL,
        position VARCHAR2(50),
        phone_number VARCHAR2(20),
        Email VARCHAR2(100),
        CONSTRAINT pk_employee PRIMARY KEY (employee_id)
    );

-- Holiday_calendar table creation
 CREATE TABLE holiday_calendar (
        holiday_id NUMBER,
        holiday_name VARCHAR2(100) NOT NULL,
        holiday_date DATE NOT NULL,
        holiday_type VARCHAR2(50),
        CONSTRAINT pk_holiday PRIMARY KEY (holiday_id)
    );

-- Audit_log table creation
CREATE TABLE audit_log (
    audit_id NUMBER PRIMARY KEY,
    table_name VARCHAR2(50) NOT NULL,
    operation VARCHAR2(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    record_id NUMBER,
    employee_id NUMBER,              -- Links to employees table
    attempt_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    attempt_user VARCHAR2(100),      -- Database username
    employee_name VARCHAR2(100),     -- Employee full name from employees table
    attempt_status VARCHAR2(20) NOT NULL, -- 'SUCCESS', 'DENIED', 'ERROR'
    error_message VARCHAR2(500),
    ip_address VARCHAR2(50),
    
    CONSTRAINT fk_audit_employee FOREIGN KEY (employee_id) 
        REFERENCES employees(employee_id) ON DELETE SET NULL
);
-- Sequence for audit IDs
CREATE SEQUENCE audit_sequence START WITH 1 INCREMENT BY 1;
