-- Passenger table creation
CREATE TABLE PASSENGER (passenger_id NUMBER(10) PRIMARY KEY, 
full_name VARCHAR(200) NOT NULL, 
national_id VARCHAR(50) UNIQUE,
phone_number VARCHAR(20) NOT NULL);

-- bus table creation
CREATE TABLE bus (
    bus_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR2(20) NOT NULL UNIQUE,
    driver_name VARCHAR2(100),
    route VARCHAR2(100)
);

-- Emergency_contact table creation
CREATE TABLE EMERGENCY_CONTACT (
    contact_id NUMBER(10) PRIMARY KEY,
    passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
    contact_name VARCHAR2(200),
    relationship VARCHAR2(50),
    contact_phone VARCHAR2(20)
    );

-- Trip table creation
CREATE TABLE EMERGENCY_CONTACT (
   contact_id NUMBER(10) PRIMARY KEY,
   passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
   contact_name VARCHAR2(200),
   relationship VARCHAR2(50),
   contact_phone VARCHAR2(20)
   );

-- booking table creation
CREATE TABLE BOOKING (
   booking_id NUMBER(10) PRIMARY KEY,
   trip_id NUMBER(10) REFERENCES TRIP(trip_id),
   passenger_id NUMBER(10) REFERENCES PASSENGER(passenger_id),
   seat_number VARCHAR2(10),
   ticket_number VARCHAR2(50) UNIQUE
   );

-- Employees table creation
  CREATE TABLE EMPLOYEES(	
  EMPLOYEE_ID NUMBER PRIMARY KEY , 
	USERNAME VARCHAR2(50) NOT NULL, 
	POSITION VARCHAR2(50), 
	EMAIL VARCHAR2(100), 
	PHONE_NUMBER VARCHAR2(20)
  );
-- Holiday_calendar table creation
 CREATE TABLE HOLIDAY_CALENDAR 
  (HOLIDAY_ID NUMBER PRIMARY KEY , 
	HOLIDAY_NAME VARCHAR2(100) NOT NULL, 
	HOLIDAY_DATE DATE NOT NULL, 
	HOLIDAY_TYPE VARCHAR2(50)
   );

-- Audit_log table creation
CREATE TABLE audit_log (
audit_id NUMBER PRIMARY KEY, 
table_name VARCHAR (50) NOT NULL, 
operation VARCHAR2(10) NOT NULL,
record_id NUMBER,
Emmployee_id NUMBER,
attempt_time TIMESTAMP DEFAULT SYSTIMESTAMP, 
attempt_user VARCHARZ (100), 
employee_name VARCHAR2(100),
attempt_status VARCHARZ(20) NOT NULL,
error message VARCHAR2 (500), 
ip_address VARCHAR (50),
CONSTRAINT fk_audit_employee FOREIGN KEY (employee_id)
REFERENCES employees (employee_id) ON DELETE SET NULL);
CREATE SEQUENCE audit_sequence START WITH 1 INCREMENT BY 1;
